const teachersLocal = [];
const membersLocal = [
	{
		id: 1,
		class: 'T2',
		name: 'Ha Minh Chau',
		vi_name: 'Hà Minh Châu',
		desc: 'I am a buffalo!',
		photo: './src/img/ava1.jpg',
		email: 'mailto:chauhm.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/profile.php?id=100049168088455',
	},
	{
		id: 2,
		class: 'T2',
		name: 'Nguyen Thi Hong Dung',
		vi_name: 'Nguyễn Thị Hồng Dung',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:dungnth.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/profile.php?id=100028449497584',
	},
	{
		id: 3,
		class: 'T2',
		name: 'Dinh Tien Dung',
		vi_name: 'Đinh Tiến Dũng',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:dungdt.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/no.oatoao',
	},
	{
		id: 4,
		class: 'T2',
		name: 'Huynh Binh Duong',
		vi_name: 'Huỳnh Bình Dương',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:duonghb.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100049176810414/',
	},
	{
		id: 5,
		class: 'T2',
		name: 'Le Nguyen Anh Duy',
		vi_name: 'Lê Nguyễn Anh Duy',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:duylna.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100058590596378/',
	},
	{
		id: 6,
		class: 'T2',
		name: 'Vu Tran Thu Ha',
		vi_name: 'Vũ Trần Thu Hà',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:havtt.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/profile.php?id=100078631712955',
	},
	{
		id: 7,
		class: 'T2',
		name: 'Tran Huy Hoang',
		vi_name: 'Trần Huy Hoàng',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:hoangth.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100030901999958/',
	},
	{
		id: 8,
		class: 'T2',
		name: 'Nguyen Bach Khoa',
		vi_name: 'Nguyễn Bách Khoa',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:khoanb.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100022934833093/',
	},
	{
		id: 9,
		class: 'T2',
		name: 'Le Trung Kien',
		vi_name: 'Lê Trung Kiên',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:kienlt.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100017113159378/',
	},
	{
		id: 10,
		class: 'T2',
		name: 'Luong Thanh Loc',
		vi_name: 'Lương Thành Lộc',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:loclt.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100015294047484/',
	},
	{
		id: 11,
		class: 'T2',
		name: 'Nguyen Doan Nhat Minh',
		vi_name: 'Nguyễn Đoàn Nhật Minh',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:minhndn.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100050499575575/',
	},
	{
		id: 12,
		class: 'T2',
		name: 'Nguyen Phuoc Dang Minh',
		vi_name: 'Nguyễn Phước Đăng Minh',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:minhnpd.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100013567955534/',
	},
	{
		id: 13,
		class: 'T2',
		name: 'Nguyen Son Thanh Ngan',
		vi_name: 'Nguyễn Sơn Thanh Ngân',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:ngannst.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100013960335966/',
	},
	{
		id: 14,
		class: 'T2',
		name: 'Do Bao Ngoc',
		vi_name: 'Đỗ Bảo Ngọc',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:ngocdb.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100020690148930/',
	},
	{
		id: 15,
		class: 'T2',
		name: 'Tran Quoc Nhat',
		vi_name: 'Trần Quốc Nhật',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:nhattq.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100014882071736/',
	},
	{
		id: 16,
		class: 'T2',
		name: 'Tran Thi Tuyet Nhu',
		vi_name: 'Trần Thị Tuyết Như',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:nhuttt.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100022005671355/',
	},
	{
		id: 17,
		class: 'T2',
		name: 'Dang Quan Phu',
		vi_name: 'Đặng Quan Phú',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:phudq.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100025292852769/',
	},
	{
		id: 18,
		class: 'T2',
		name: 'Vu Nguyen Minh Quang',
		vi_name: 'Vũ Nguyễn Minh Quang',
		desc: 'Ahihi do ngu',
		photo: './src/img/ava1.jpg',
		email: 'mailto:quangvnm.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/profile.php?id=100027961743727',
	},
	{
		id: 19,
		class: 'T2',
		name: 'Nguyen Cam Tho',
		vi_name: 'Nguyễn Cẩm Thơ',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:thonc.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100054764538518/',
	},
	{
		id: 20,
		class: 'T2',
		name: 'Khuong Ngoc Toan',
		vi_name: 'Khương Ngọc Toàn',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:toankn.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100034608337829/',
	},
	{
		id: 21,
		class: 'T2',
		name: 'Nguyen Thi Huyen Trang',
		vi_name: 'Nguyễn Thị Huyền Trang',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:trangnth.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100028360153052/',
	},
	{
		id: 22,
		class: 'T2',
		name: 'Ngo Minh Tri',
		vi_name: 'Ngô Minh Trí',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:trinm.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100048426810259/',
	},
	{
		id: 23,
		class: 'T2',
		name: 'Truong Hoang Y',
		vi_name: 'Trương Hoàng Ý',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:yth.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100011289947534/',
	},
	{
		id: 24,
		class: 'T2',
		name: 'Tran Hoang Ngoc Yen',
		vi_name: 'Trần Hoàng Ngọc Yến',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:yenthn.t2.2023@gmail.com',
		facebook: 'https://www.facebook.com/100049423807451/',
	},
	{
		id: 25,
		class: 'Ti',
		name: 'Dang Minh Anh',
		vi_name: 'Đặng Minh Ánh',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:anhdm.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100035896567750/',
	},
	{
		id: 26,
		class: 'Ti',
		name: 'Tang Xuan Bac',
		vi_name: 'Tăng Xuân Bắc',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:bactx.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100017814251455/',
	},
	{
		id: 27,
		class: 'Ti',
		name: 'Ly Gia Binh',
		vi_name: 'Lý Gia Bình',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:binhlg.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100012140252357/',
	},
	{
		id: 28,
		class: 'Ti',
		name: 'Dao Tuan Duy',
		vi_name: 'Đào Tuấn Duy',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:duydt.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/ec.duy.9/',
	},
	{
		id: 29,
		class: 'Ti',
		name: 'Trinh Chan Duy',
		vi_name: 'Trịnh Chấn Duy',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:duytc.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100009247686862/',
	},
	{
		id: 30,
		class: 'Ti',
		name: 'Tran Le Van Khanh',
		vi_name: 'Trần Lê Vân Khanh',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:khanhtlv.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100042853937221/',
	},
	{
		id: 31,
		class: 'Ti',
		name: 'Yuran Legends',
		vi_name: 'Ngô Nguyễn Thế Khoa',
		desc: 'Nothing can stop me !!!',
		photo: './src/img/ava1.jpg',
		email: 'mailto:trieuvanbd123@gmail.com',
		facebook: 'https://www.facebook.com/YuranLegends/',
	},
	{
		id: 32,
		class: 'Ti',
		name: 'Nguyen Dinh Manh',
		vi_name: 'Nguyễn Đình Mạnh',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'manhnd.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100012655329823/',
	},
	{
		id: 33,
		class: 'Ti',
		name: 'Tran Quang Thanh',
		vi_name: 'Trần Quang Thành',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:thanhtq.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100022862094344/',
	},
	{
		id: 34,
		class: 'Ti',
		name: 'Huynh Duc Tin',
		vi_name: 'Huỳnh Đức Tín',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:tinhd.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100055966183205/',
	},
	{
		id: 35,
		class: 'Ti',
		name: 'Le Hong Vu',
		vi_name: 'Lê Hồng Vũ',
		desc: '',
		photo: './src/img/ava1.jpg',
		email: 'mailto:vulh.ti.2023@gmail.com',
		facebook: 'https://www.facebook.com/100024492489395/',
	},
];
const localData = [teachersLocal, membersLocal];
